channels:
- anaconda
- conda-forge
dependencies:
- python=3.8.5
- pip:
  - numpy==1.23.5
  - pandas==1.5.2
  - scikit-learn==1.1.3
  - tensorflow==2.12.0
  - keras==2.12.0
  - ipykernel==6.8.0
  - azureml-core == 1.49.0
  - azureml-mlflow==1.49.0
  - psutil==5.9.4
  - azureml-inference-server-http==0.8.4
  - azureml-dataset-runtime == 1.49.0

name: TrainMLModel
